### ISSUE TITLE
THEME_CONTACT_EMAIL vs CONTACT_EMAIL

### ISSUE THREAD

**Issue by jtauber** [pinax/pinax-templates#10]
Templates use `THEME_CONTACT_EMAIL` but the context provider in https://github.com/pinax/pinax-starter-projects/blob/account/project_name/context_processors.py#L24 uses `CONTACT_EMAIL`

**Comment by KatherineMichel** [comment]
I can fix this. Is one preferred over the other? @jtauber

**Comment by KatherineMichel** [comment]
Closing issue. Should be dealt with through PR #12
