### ISSUE TITLE
Call for Maintainers

### ISSUE THREAD

**Issue by paltman** [pinax/pinax-templates#18]
Looking for maintainers!

There is a lot of pull requests and open issues that the current maintainers, myself included, are just not finding the time to properly get to.

Maybe you've submitted some PRs and are frustrated with the lack of attention. Maybe you use this project in one or more of your projects and want to see that it is properly carried forward.

Whatever you reasons may be, let me know if you have interest and I'll add you to the repo and to PyPI (will need your PyPI name).

Preference will go to those who have commits on this repo and/or have shown an active interest in the issues.

Thanks!
Patrick

**Comment by uhurusurfa** [comment]
@paltman  Please add me to this project. Bump.

**Comment by uhurusurfa** [comment]
@KatherineMichel - can you add me please? This project is prevnitng upgrading pinax teams

**Comment by uhurusurfa** [comment]
@grahamu - can you add me to the project please?

**Comment by uhurusurfa** [comment]
@paltman @gregnewman @brosner  - can anyone add me please?

**Comment by paltman** [comment]
@uhurusurfa added here and to PyPi.  Thanks!

**Comment by uhurusurfa** [comment]
@paltman - Thanks. Can you add @martin-marty to this repo as well otherwise I will be stuck with PR's that do not get merged.

**Comment by paltman** [comment]
@uhurusurfa @martin-marty done
